//
//  IdentifierType.swift
//  
//
//  Created by Ian Sampson on 2021-11-14.
//

enum IdentifierType: String {
    case shelfMark = "http://id.loc.gov/ontologies/bibframe/ShelfMark"
    case shelfMarkDdc = "http://id.loc.gov/ontologies/bibframe/ShelfMarkDdc"
    case shelfMarkLcc = "http://id.loc.gov/ontologies/bibframe/ShelfMarkLcc"
    case shelfMarkNlm = "http://id.loc.gov/ontologies/bibframe/ShelfMarkNlm"
    case shelfMarkUdc = "http://id.loc.gov/ontologies/bibframe/ShelfMarkUdc"
    case accessionNumber = "http://id.loc.gov/ontologies/bibframe/AccessionNumber"
    case ansi = "http://id.loc.gov/ontologies/bibframe/Ansi"
    case audioIssueNumber = "http://id.loc.gov/ontologies/bibframe/AudioIssueNumber"
    case audioTake = "http://id.loc.gov/ontologies/bibframe/AudioTake"
    case barcode = "http://id.loc.gov/ontologies/bibframe/Barcode"
    case coden = "http://id.loc.gov/ontologies/bibframe/Coden"
    case copyrightNumber = "http://id.loc.gov/ontologies/bibframe/CopyrightNumber"
    case dissertationIdentifier = "http://id.loc.gov/ontologies/bibframe/DissertationIdentifier"
    case doi = "http://id.loc.gov/ontologies/bibframe/Doi"
    case ean = "http://id.loc.gov/ontologies/bibframe/Ean"
    case eidr = "http://id.loc.gov/ontologies/bibframe/Eidr"
    case fingerprint = "http://id.loc.gov/ontologies/bibframe/Fingerprint"
    case gtin14Number = "http://id.loc.gov/ontologies/bibframe/Gtin14Number"
    case hdl = "http://id.loc.gov/ontologies/bibframe/Hdl"
    case isan = "http://id.loc.gov/ontologies/bibframe/Isan"
    case isbn = "http://id.loc.gov/ontologies/bibframe/Isbn"
    case ismn = "http://id.loc.gov/ontologies/bibframe/Ismn"
    case isni = "http://id.loc.gov/ontologies/bibframe/Isni"
    case iso = "http://id.loc.gov/ontologies/bibframe/Iso"
    case isrc = "http://id.loc.gov/ontologies/bibframe/Isrc"
    case issn = "http://id.loc.gov/ontologies/bibframe/Issn"
    case issnL = "http://id.loc.gov/ontologies/bibframe/IssnL"
    case istc = "http://id.loc.gov/ontologies/bibframe/Istc"
    case iswc = "http://id.loc.gov/ontologies/bibframe/Iswc"
    case lcOverseasAcq = "http://id.loc.gov/ontologies/bibframe/LcOverseasAcq"
    case lccn = "http://id.loc.gov/ontologies/bibframe/Lccn"
    case local = "http://id.loc.gov/ontologies/bibframe/Local"
    case matrixNumber = "http://id.loc.gov/ontologies/bibframe/MatrixNumber"
    case musicDistributorNumber = "http://id.loc.gov/ontologies/bibframe/MusicDistributorNumber"
    case musicPlate = "http://id.loc.gov/ontologies/bibframe/MusicPlate"
    case musicPublisherNumber = "http://id.loc.gov/ontologies/bibframe/MusicPublisherNumber"
    case nbn = "http://id.loc.gov/ontologies/bibframe/Nbn"
    case postalRegistration = "http://id.loc.gov/ontologies/bibframe/PostalRegistration"
    case publisherNumber = "http://id.loc.gov/ontologies/bibframe/PublisherNumber"
    case reportNumber = "http://id.loc.gov/ontologies/bibframe/ReportNumber"
    case sici = "http://id.loc.gov/ontologies/bibframe/Sici"
    case stockNumber = "http://id.loc.gov/ontologies/bibframe/StockNumber"
    case strn = "http://id.loc.gov/ontologies/bibframe/Strn"
    case studyNumber = "http://id.loc.gov/ontologies/bibframe/StudyNumber"
    case upc = "http://id.loc.gov/ontologies/bibframe/Upc"
    case urn = "http://id.loc.gov/ontologies/bibframe/Urn"
    case videoRecordingNumber = "http://id.loc.gov/ontologies/bibframe/VideoRecordingNumber"
}
